# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and typescript for building
COPY package.json package-lock.json tsconfig.json ./
RUN npm install && npm install typescript

# Copy source and build
COPY src ./src
RUN npx tsc

# Stage 2: production
FROM node:lts-alpine
WORKDIR /app

# Install runtime dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy built files
COPY --from=builder /app/dist ./dist

# Default command
ENTRYPOINT ["node", "dist/index.js"]
